### ISSUE TITLE
Could you share your paper to me?

### ISSUE THREAD

**Issue by pengboyemo** [zhh2005757/FAST-LIO-Multi-Sensor-Fusion#12]
@zhh2005757
Hi, thanks for your work, could you share your paper about "Vehicle-Motion-Constraint-Based Visual-Inertial-Odometer Fusion With OnlineExtrinsicCalibration" to me, thanks.

**Comment by zhh2005757** [comment]
> @zhh2005757
> Hi, thanks for your work, could you share your paper about "Vehicle-Motion-Constraint-Based Visual-Inertial-Odometer Fusion With OnlineExtrinsicCalibration" to me, thanks.

oh please let me know your email then I can send it to you

**Comment by pengboyemo** [comment]
254959935@qq.com, thansk again.

**Comment by pengboyemo** [comment]
> > @zhh2005757
> > Hi, thanks for your work, could you share your paper about "Vehicle-Motion-Constraint-Based Visual-Inertial-Odometer Fusion With OnlineExtrinsicCalibration" to me, thanks.
> 
> oh please let me know your email then I can send it to you

I have received your paper, thanks.
