### ISSUE TITLE
Question for citation

### ISSUE THREAD

**Issue by TakuOkawara** [zhh2005757/FAST-LIO-Multi-Sensor-Fusion#2]
We decide to cite this project for our paper. Therefore, we cite this GitHub page and the following paper mentioned in this GitHub page.
@ARTICLE{10272296,
  author={Zhao, Hang and Ji, Xinchun and Wei, Dongyan},
  journal={IEEE Sensors Journal}, 
  title={Vehicle-Motion-Constraint-Based Visual-Inertial-Odometer Fusion With Online Extrinsic Calibration}, 
  year={2023},
  volume={23},
  number={22},
  pages={27895-27908},
  keywords={Odometers;Calibration;Wheels;Velocity measurement;Sensors;Cameras;Visualization;Extrinsic calibration;robust initialization;vehicle motion constraint;visual-inertial-odometer fusion},
  doi={10.1109/JSEN.2023.3319345}}

The first author of this paper is Mr. "Hang Zhao", and then the creator name of this GitHub page is "HickeyZhao". 
We'd like to make sure, just in case, **Could you tell us whether Mr. "Hang Zhao" and "HickeyZhao"  are identical?**

**Comment by zhh2005757** [comment]
Sorry for causing confusion. They are identical, Hickey is my English nick name. I updated my profile with Hang Zhao to make it consistent with the listed paper.

**Comment by TakuOkawara** [comment]
@zhh2005757 
Thank you very much for your quick and polite support!!
