### ISSUE TITLE
关于融合轮速，速度残差的计算疑问

### ISSUE THREAD

**Issue by minghongss** [zhh2005757/FAST-LIO-Multi-Sensor-Fusion#4]
V3D res = wheel_v_vec * s.wheel_s - s.offset_R_W_I.toRotationMatrix().transpose() * (s.rot.toRotationMatrix().transpose() * s.vel + angv_crossmat * s.offset_T_W_I);
您好作者，我想问下这行代码对应的公式是您引用论文的公式（2）吗？s.wheel_s 这个含义是什么呢？我对比了代码和公式，并不匹配，是我哪里出现了错误吗

**Comment by zhh2005757** [comment]
那个是轮速的比例因子，轮速计是需要标定的，因为轮速计的原理是计算秒脉冲，然后乘以轮胎半径得到速度，而轮胎直径会随着轮胎的磨损以及车身自重的不同而不同，从而影响最终的轮速。实际的轮速与真实车辆前行速度之间差一个比例因子s，这个也是可以在线估计出来的。

**Comment by minghongss** [comment]
理解了，关于公式部分我也推导出来了，感谢您的工作！
