### ISSUE TITLE
请问更新怎么使用gnss数据的？

### ISSUE THREAD

**Issue by JiangWeiHn** [zhh2005757/FAST-LIO-Multi-Sensor-Fusion#6]
感谢您开源融合gnss信号的fast-lio。但我有2个疑。
1.在更新gnss信息时，程序是这样的：
       if (meas.gnss.front()->pose.covariance[0] < 200) // 航向初始化未完成或gnss水平噪声大于200不进行更新（遮挡区域）
                    {
                        kf_state.update_iterated_dyn_share(); // gnss更新
                        ROS_WARN("gnss update !");
                    }else{
                        ROS_WARN("gnss too noise !");
                    }
我没看到数据传入kf_state中，这个是怎么更新的？

2 这个meas.gnss内保存的是gnss_buffer里的数据，但gnss_buffer里的数据没有经过GNSS_Heading转换，还是在enu坐标系下，这个和我的imu的前左上坐标系不一致，不需要转换么？

**Comment by zhh2005757** [comment]
1. update_iterated_dyn_share()会调用在lasermapping.cpp下定义的h_share_model函数，里面定义了gnss的更新方式
2. enu到imu坐标系的航向在h_share_model里在线估计了，用于对齐两个坐标系

**Comment by JiangWeiHn** [comment]
收到，谢谢回复
