### ISSUE TITLE
求助，gnss和激光的轨迹对不上！

### ISSUE THREAD

**Issue by JiangWeiHn** [zhh2005757/FAST-LIO-Multi-Sensor-Fusion#7]
我imu是前左上坐标系，小车开始静止状态下，航向角在enu坐标系下是-53°（采用imu和gnss组合导航得到的。
跑您的程序，GNSS_Heading的初始状态为-132°，感觉不差多少啊。但gnss轨迹飞了。不知道为什么？下面是我跑的图，激光雷达的轨迹基本正常。
![Screenshot from 2024-07-10 17-38-42](https://github.com/zhh2005757/FAST-LIO-Multi-Sensor-Fusion/assets/24561984/6e81c516-01b6-4cea-9f31-79e10c2b3444)

**Comment by zhh2005757** [comment]
你是固定了GNSS_Heading吗还是在线估计的，因为我GNSS轨迹显示的部分是用了GNSS_Heading转换到IMU坐标系下的，可以看一下这部分代码，确定一下是显示的问题还是融合的问题

**Comment by JiangWeiHn** [comment]
用的您的源程序，没有改代码。航向角在enu坐标系下是-53°，这个是另外的组合导航的计算结果。可能是融合的问题，显示的我看了您的程序，是转换过的。

**Comment by zhh2005757** [comment]
怀疑是融合的问题的话，可以把lidar关掉看看GNSS和IMU的融合是否正确，因为lidar默认的权重比较高有时候可能看不出来融合的问题。另外，可以直接把组合导航对准的航向赋值给GNSS_Heading，然后注释掉在线估计航向的代码，看一下融合是否正确，注意坐标系的不同，我的代码都是融合到IMU坐标系的不是ENU。

**Comment by JiangWeiHn** [comment]
好的，谢谢
