### ISSUE TITLE
关于rs数据的结构

### ISSUE THREAD

**Issue by JiangWeiHn** [zhh2005757/FAST-LIO-Multi-Sensor-Fusion#8]
您的rs雷达的数据结构的定义如下：
      namespace rslidar_ros {
    struct EIGEN_ALIGN16 Point {
        PCL_ADD_POINT4D;
        float intensity;
        float time;
        uint16_t ring;
        EIGEN_MAKE_ALIGNED_OPERATOR_NEW
    };
}  // namespace rslidar_ros
POINT_CLOUD_REGISTER_POINT_STRUCT(rslidar_ros::Point,
                                  (float, x, x)
                                  (float, y, y)
                                  (float, z, z)
                                  **(float, intensity, curvature)
                                  (float, time, normal_x)**
                                  (uint16_t, ring, ring)
)
这里的time和intensity对应的是不是错了? 我运行的时候，看着不太对。

**Comment by zhh2005757** [comment]
rslidar相关测试不多，我只跑过HILTI的几个序列似乎没有问题，具体的可以爬爬文应该有不少关于fastlio适配rslidar的教程

**Comment by JiangWeiHn** [comment]
好的
